### ISSUE TITLE
ASL CALIB M0t.nii.gz

### ISSUE THREAD

**Issue by tjmanson** [ibme-qubic/asl-docs#3]
Hi there,

I've been using asl_calib (saturation recovery mode). I am wondering what the output image M0t.nii.gz is, and how it relates to the arterial magnetization estimate in the M0.txt file? I couldn't find anything in the documentation about it... 

Thanks!

**Comment by machappell** [comment]
This the saturation recovery curve fitting within the brain mask - using prior values that would be appropriate for tissue. This is part of the process of generating the T1 estimate map and is meant to be an estimate of the tissue M0. But, it is not what is sued to estimate M0 in the CSF - a separate fit within the ventricle mask is done for that, since the T1 is quite so different. That is generally what is used to calculate the M0.txt value.

**Comment by mcraig-ibme** [comment]
Closing as query answered and no other issue to address
